/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2024-05-01")
public enum InvalidArgumentType implements org.apache.thrift.TEnum {
  NOCD(1),
  WRONGDEVICETYPE(2),
  CDALREADYIN(3),
  WRONGRADIOSTATION(4);

  private final int value;

  private InvalidArgumentType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static InvalidArgumentType findByValue(int value) { 
    switch (value) {
      case 1:
        return NOCD;
      case 2:
        return WRONGDEVICETYPE;
      case 3:
        return CDALREADYIN;
      case 4:
        return WRONGRADIOSTATION;
      default:
        return null;
    }
  }
}
